# -*- coding: utf-8 -*-
"""Sentimental_analysis_on_movie_reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_EnL-ZuRYSw5l8_Ud59tKKQMp63TuAN
"""

!pip install pandas scikit-learn nltk transformers tensorflow

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
# Update the path to where you saved the file in your Drive
file_path = '/content/drive/My Drive/train.tsv'
df = pd.read_csv(file_path, sep='\t')
print(df.head())

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()  # Lowercase
    text = re.sub(r'[^\w\s]', '', text) # Remove punctuation
    tokens = text.split() # Tokenize
    tokens = [word for word in tokens if word not in stop_words] # Remove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens] # Lemmatize
    return " ".join(tokens)

# Apply the preprocessing
df['Cleaned_Phrase'] = df['Phrase'].apply(preprocess_text)

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Define features (X) and labels (y)
X = df['Cleaned_Phrase']
y = df['Sentiment']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a vectorizer for unigrams + bigrams (as the paper found this worked best)
# ngram_range=(1, 2) means it will use both single words and pairs of words
vectorizer = CountVectorizer(ngram_range=(1, 2))

# Fit and transform the training data
X_train_vec = vectorizer.fit_transform(X_train)

# Only transform the test data
X_test_vec = vectorizer.transform(X_test)

# --- SETUP CELL: Common imports and reusable functions ---
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

# Optional: to silence softmax warning (newer sklearn)
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

def evaluate_model(model, X_train, X_test, y_train, y_test, model_name):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"=== {model_name} ===")
    print(f"Accuracy: {acc:.4f}")
    print(classification_report(y_test, preds))
    return acc

# --- SEPARATE UNIGRAM & BIGRAM FEATURE EXPERIMENTS ---

# UNIGRAM
uni_vectorizer = CountVectorizer(ngram_range=(1, 1))
X_train_uni = uni_vectorizer.fit_transform(X_train)
X_test_uni = uni_vectorizer.transform(X_test)

# BIGRAM
bi_vectorizer = CountVectorizer(ngram_range=(2, 2))
X_train_bi = bi_vectorizer.fit_transform(X_train)
X_test_bi = bi_vectorizer.transform(X_test)

results_sep = []

# 1. NBC - Unigram & Bigram
nb_uni_acc = evaluate_model(MultinomialNB(alpha=1.0), X_train_uni, X_test_uni, y_train, y_test, "Naive Bayes - Unigram")
results_sep.append(('NBC - Unigram', nb_uni_acc))

nb_bi_acc = evaluate_model(MultinomialNB(alpha=1.0), X_train_bi, X_test_bi, y_train, y_test, "Naive Bayes - Bigram")
results_sep.append(('NBC - Bigram', nb_bi_acc))


# 2. Softmax - Unigram & Bigram
softmax_uni = LogisticRegression(solver='lbfgs', max_iter=2000, C=1.0)
softmax_uni_acc = evaluate_model(softmax_uni, X_train_uni, X_test_uni, y_train, y_test, "Softmax - Unigram")
results_sep.append(('Softmax - Unigram', softmax_uni_acc))

softmax_bi = LogisticRegression(solver='lbfgs', max_iter=2000, C=1.0)
softmax_bi_acc = evaluate_model(softmax_bi, X_train_bi, X_test_bi, y_train, y_test, "Softmax - Bigram")
results_sep.append(('Softmax - Bigram', softmax_bi_acc))


# 3. SVM - Unigram & Bigram
svm_uni = LinearSVC(max_iter=1000)
svm_uni_acc = evaluate_model(svm_uni, X_train_uni, X_test_uni, y_train, y_test, "SVM - Unigram")
results_sep.append(('SVM - Unigram', svm_uni_acc))

svm_bi = LinearSVC(max_iter=1000)
svm_bi_acc = evaluate_model(svm_bi, X_train_bi, X_test_bi, y_train, y_test, "SVM - Bigram")
results_sep.append(('SVM - Bigram', svm_bi_acc))

# Create comparison table
df_sep = pd.DataFrame(results_sep, columns=['Model', 'Accuracy'])
print("\n=== Separate N-Grams Results ===")
print(df_sep)

# --- COMBINED UNIGRAM + BIGRAM FEATURE EXPERIMENTS ---
combined_vectorizer = CountVectorizer(ngram_range=(1, 2))
X_train_combined = combined_vectorizer.fit_transform(X_train)
X_test_combined = combined_vectorizer.transform(X_test)

results_combined = []

# NBC
nb_combined_acc = evaluate_model(MultinomialNB(alpha=1.0), X_train_combined, X_test_combined, y_train, y_test, "Naive Bayes - Combined")
results_combined.append(('NBC - Combined', nb_combined_acc))

# Softmax
softmax_combined = LogisticRegression(solver='lbfgs', max_iter=2000, C=1.0)
softmax_combined_acc = evaluate_model(softmax_combined, X_train_combined, X_test_combined, y_train, y_test, "Softmax - Combined")
results_combined.append(('Softmax - Combined', softmax_combined_acc))

# SVM
svm_combined = LinearSVC(max_iter=1000)
svm_combined_acc = evaluate_model(svm_combined, X_train_combined, X_test_combined, y_train, y_test, "SVM - Combined")
results_combined.append(('SVM - Combined', svm_combined_acc))

# Create comparison table
df_combined = pd.DataFrame(results_combined, columns=['Model', 'Accuracy'])
print("\n=== Combined N-Grams Results ===")
print(df_combined)

# Representation of the results in one table for easy presentation
final_results = pd.concat([df_sep, df_combined], ignore_index=True)
print("\n=== Final Model Comparison ===")
print(final_results.sort_values(by='Accuracy', ascending=False))

#=========================
# Setup for BERT & BILSTM
#=========================
!pip install transformers torch tqdm --quiet

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from tqdm import tqdm
from google.colab import drive

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# ============================
# BERT - Dataset & Model
# ============================
from transformers import BertTokenizer, BertForSequenceClassification

# Load tokenizer & model
num_labels = len(set(y_train))  # assuming y_train already defined
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_labels)
model.to(device)

# Dataset class
class ReviewDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=64):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_len,
            return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

train_dataset = ReviewDataset(X_train.tolist(), y_train.tolist(), tokenizer)
test_dataset = ReviewDataset(X_test.tolist(), y_test.tolist(), tokenizer)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

# ============================
# BERT - Training
# ============================
optimizer = AdamW(model.parameters(), lr=2e-5)
epochs = 1

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Training Epoch {epoch+1}"):
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1} - Loss: {total_loss/len(train_loader):.4f}")

# ============================
# BERT - Save Model
# ============================
bert_save_path = "/content/drive/MyDrive/bert_sentiment_model"
model.save_pretrained(bert_save_path)
tokenizer.save_pretrained(bert_save_path)
print("BERT model saved to:", bert_save_path)

# ============================
# ♻️ BERT - Load Model
# ============================
from transformers import BertTokenizer, BertForSequenceClassification

tokenizer = BertTokenizer.from_pretrained(bert_save_path)
model = BertForSequenceClassification.from_pretrained(bert_save_path)
model.to(device)
model.eval()
print("BERT model loaded.")

# ============================
# BERT - Inference Demo
# ============================
def predict_sentiment_bert(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
        pred = torch.argmax(outputs.logits, dim=1).item()
    return pred

# Try it
sample = "The movie was fantastic and emotional!"
print("Predicted Sentiment:", predict_sentiment_bert(sample))

# ============================
# BERT + BiLSTM Model Definition
# ============================
import torch.nn as nn
from transformers import BertModel

class BertBiLSTM(nn.Module):
    def __init__(self, bert_model_name='bert-base-uncased', hidden_dim=128, num_classes=5, dropout=0.3):
        super(BertBiLSTM, self).__init__()
        self.bert = BertModel.from_pretrained(bert_model_name)
        self.lstm = nn.LSTM(input_size=768,
                            hidden_size=hidden_dim,
                            num_layers=1,
                            batch_first=True,
                            bidirectional=True)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim * 2, num_classes)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = outputs.last_hidden_state  # (batch, seq_len, 768)

        lstm_out, _ = self.lstm(sequence_output)
        # Take the last hidden state from BiLSTM
        last_hidden = lstm_out[:, -1, :]
        last_hidden = self.dropout(last_hidden)
        logits = self.fc(last_hidden)
        return logits

num_labels = len(set(y_train))
model_bert_bilstm = BertBiLSTM(num_classes=num_labels).to(device)

# ============================
# TRAINING: BERT + BiLSTM
# ============================
from torch.optim import AdamW
from tqdm import tqdm

optimizer_bert_bilstm = AdamW(model_bert_bilstm.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()
epochs = 3

model_bert_bilstm.train()
for epoch in range(epochs):
    total_loss = 0
    progress_bar = tqdm(train_loader, desc=f"BERT+BiLSTM Epoch {epoch+1}")

    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        optimizer_bert_bilstm.zero_grad()
        outputs = model_bert_bilstm(input_ids, attention_mask)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_bert_bilstm.step()

        total_loss += loss.item()
        progress_bar.set_postfix({"loss": f"{total_loss/len(train_loader):.4f}"})

    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.4f}")

# ================================
# 💾 BERT + BiLSTM Save & Load
# ================================
bert_bilstm_path = "/content/drive/MyDrive/bert_bilstm_sentiment.pth"

# --- Save weights ---
torch.save(model_bert_bilstm.state_dict(), bert_bilstm_path)
print(f"✅ BERT+BiLSTM model saved to: {bert_bilstm_path}")

# --- Recreate model before loading weights ---
num_classes = len(set(y_train))
hidden_dim = 128

# Explicitly pass arguments by name
model_bert_bilstm = BertBiLSTM(bert_model_name='bert-base-uncased', hidden_dim=hidden_dim, num_classes=num_classes).to(device)
model_bert_bilstm.load_state_dict(torch.load(bert_bilstm_path, map_location=device))
model_bert_bilstm.eval()

print("✅ BERT+BiLSTM model loaded successfully.")

# ================================
# 🚀 BERT + BiLSTM Inference Demo
# ================================
def predict_sentiment_bert_bilstm(text):
    model_bert_bilstm.eval()
    inputs = tokenizer(
        text,
        return_tensors='pt',
        truncation=True,
        padding='max_length',
        max_length=128
    ).to(device)

    with torch.no_grad():
        logits = model_bert_bilstm(inputs['input_ids'], inputs['attention_mask'])
        pred = torch.argmax(logits, dim=1).item()

    return pred

# Example
sample_text = "The movie was absolutely fantastic!"
prediction = predict_sentiment_bert_bilstm(sample_text)
print(f"Predicted Sentiment: {prediction}")

# ============================
# 📊 EVALUATION: BERT & BERT+BiLSTM
# ============================
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

# --- Evaluate BERT ---
model.eval()
bert_preds = []
bert_true = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()

        bert_preds.extend(preds)
        bert_true.extend(labels.cpu().numpy())

bert_acc = accuracy_score(bert_true, bert_preds)
print(f"=== BERT Test Accuracy: {bert_acc:.4f} ===")
print(classification_report(bert_true, bert_preds))


# --- Evaluate BERT + BiLSTM ---
model_bert_bilstm.eval()
bert_bilstm_preds = []
bert_bilstm_true = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model_bert_bilstm(input_ids, attention_mask)
        preds = torch.argmax(outputs, dim=1).cpu().numpy()

        bert_bilstm_preds.extend(preds)
        bert_bilstm_true.extend(labels.cpu().numpy())

bert_bilstm_acc = accuracy_score(bert_bilstm_true, bert_bilstm_preds)
print(f"=== BERT + BiLSTM Test Accuracy: {bert_bilstm_acc:.4f} ===")
print(classification_report(bert_bilstm_true, bert_bilstm_preds))

# ============================
# 📈 FINAL COMPARISON TABLE
# ============================

final_results = pd.DataFrame({
    'Model': ['Naive Bayes', 'Softmax', 'SVM', 'BERT', 'Bert+BiLSTM'],
    'Accuracy': [nb_combined_acc,softmax_combined_acc,svm_combined_acc, bert_acc, bert_bilstm_acc]
})

final_results = final_results.sort_values(by='Accuracy', ascending=False).reset_index(drop=True)
print("=== Final Model Comparison ===")
print(final_results)

#Bar Chart
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.bar(final_results['Model'], final_results['Accuracy'], color='steelblue')
plt.ylim(0, 1)
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy')
plt.xticks(rotation=20)
for i, v in enumerate(final_results['Accuracy']):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center', fontweight='bold')
plt.show()